options:
  temperature-units:
    type: string
    default: "F"
    description: "F or C for temperature units"
  dns-addresses:
    type: string
    default: "1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001"
    description: "Up to 4 dns server addresses. Seperate with ; default are Cloudflare addresses. This config only applies if dns-over-tls and recrusive-dns are disabled."
  proxy-local:
      type: boolean
      description: "Set to True to restrict access via reverse-proxy to local address spaces"
      default: True
  proxy-subdomain:
      type: string
      description: "The subdomain to register with the reverseproxy"
      default: "pihole"
  proxy-external-port:
      type: int
      description: "External port for the proxy to listen on, typically 443."
      default: 443
  enable-dns-over-tls:
      type: boolean
      description: "Setup DNS over TLS via stubby. When enabled the local stub resolver will be used which includes upstream dns and dns-addresses config will not be used."
      default: True
  enable-recursive-dns:
      type: boolean
      description: "Setup as recrusive DNS server."
      default: True
  conditional-forwards:
      type: string
      description: "List of local domains and servers to forward them to. Comma seperated list with domain:server. Example local:192.168.1.1,vpn:10.0.0.1"
      default: ""
