#!/usr/local/sbin/charm-env python3

from charmhelpers.core import hookenv
# import sys
# sys.path.append('lib')
# sys.path.append('reactive')

from lib_pi_hole import PiholeHelper

helper = PiholeHelper()

hookenv.log('Setting pi-hole password','INFO')
helper.set_password(password=hookenv.action_get('password'))
